# Generated by Django 4.2.4 on 2023-08-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usua', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
